# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "511fb4a15be08ba3e8872de396ed8f7d"
name = "ebayimporter"
handle = "ebayimporter-1"
application_url = "https://born-detroit-delivering-hottest.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "paymenttest-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_locales,read_products,read_script_tags,read_themes,write_content,write_locales,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://born-detroit-delivering-hottest.trycloudflare.com/auth/callback",
  "https://born-detroit-delivering-hottest.trycloudflare.com/auth/shopify/callback",
  "https://born-detroit-delivering-hottest.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
