# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4abb8690be2447b20df940e5063469b"
name = "ebayimporter"
handle = "ebayimporter-2"
application_url = "https://box-icon-musical-ic.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nodestoreapp.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://box-icon-musical-ic.trycloudflare.com/auth/callback",
  "https://box-icon-musical-ic.trycloudflare.com/auth/shopify/callback",
  "https://box-icon-musical-ic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
